### ISSUE TITLE
Revamp contracts testing

### ISSUE THREAD

**Issue by odyslam** [nomad-xyz/monorepo#248]
## Motivation
- Write tests in Solidity
- Increase testing speed
- Introduce new testing primitives (prop testing)

## Solution
Migrate test suite to Foundry

### Tests

- [ ] [contracts-core](https://github.com/nomad-xyz/monorepo/pull/247)
- [ ] contracts-bridge(TBD)
- [ ] contracts-router(TBD)
- [ ] deployment (test deployment correctness via forking)
- [ ] integrate foundry tooling (node, tests, etc.) into Nomad devenv

### Deployment
- [ ] Research & Scope for foundry-based deployment pipeline
- [ ] RFC for foundry-based deployment pipeline
